name: Laravel CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker container
        run: docker-compose up -d --build

      - name: Run database migrations
        run: docker-compose exec app php artisan migrate --force
        env:
          APP_ENV: production

      - name: Run tests (optional)
        run: docker-compose exec app php artisan test

      - name: Deploy to server (using SSH)
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/your-app
            git pull origin main
            docker-compose up -d --build
